import * as React from "react";
import { Link, useStaticQuery, graphql } from "gatsby";
import { ReactNode } from "react";
import {
  container,
  heading,
  navLinks,
  navLinkItem,
  navLinkText,
  siteTitle,
  footer,
  main,
} from "./layout.module.css";
import { format } from "date-fns";

const NaviItem = ({ path, view }: { path: string; view: string }) => (
  <li className={navLinkItem}>
    <Link to={path} className={navLinkText}>
      {view}
    </Link>
  </li>
);

export const Layout = ({
  pageTitle,
  children,
}: {
  pageTitle: string;
  children: ReactNode;
}) => {
  const data = useStaticQuery(graphql`
    query MyQuery {
      site {
        siteMetadata {
          title
        }
      }
    }
  `);

  return (
    <div className={container}>
      <title>
        {pageTitle} | {data.site.siteMetadata.title}
      </title>
      <header className={siteTitle}>{data.site.siteMetadata.title}</header>
      <nav>
        <ul className={navLinks}>
          {[
            { path: "/", view: "Home" },
            { path: "/about", view: "About" },
            { path: "/blog", view: "Blogs" },
          ].map((n) => (
            <NaviItem key={n.view} {...n} />
          ))}
        </ul>
      </nav>
      <main className={main}>
        <h1 className={heading}>{pageTitle}</h1>
        {children}
      </main>
      <footer className={footer}>
        {`©tokiorush ${format(new Date(), "yyyy")} 
        This site is generated by `}
        <a href="https://www.gatsbyjs.com/">Gatsby</a>.
      </footer>
    </div>
  );
};
